Use `walk!` in bacterial growth example
JuliaDynamics/Agents.jl pull request #548
Opened 2021-08-28 16:09 UTC by MichielStock

Addresses #544, though does not solve it.

2021-08-30 14:48 UTC, AayushSabharwal commented
I think this looks good. Maybe address the `add_agent!` issue here too?

2021-10-31 19:37 UTC, Datseris commented
bump @MichielStock can you address the `add_agent!` here as Aayush suggested?

2021-11-01 12:36 UTC, MichielStock commented
I added a check now. It runs with an unlimited number of bacteria now, as they now completely remain in the space.

2021-11-01 12:49 UTC, Datseris requested changes

2021-11-01 12:49 UTC, Datseris commented on examples/growing_bacteria.jl
> +            all(0 .≤ a.p1 .≤ extent) && add_agent!(a.p1, model, 0.0, a.orientation, 0.0, 0.1 * rand(model.rng) + 0.05)
```suggestion
            all(0 .≤ a.p1 .< extent) && add_agent!(a.p1, model, 0.0, a.orientation, 0.0, 0.1 * rand(model.rng) + 0.05)
```
As discussed in the issue, if the position is _equal_ to the extent, it is out of bounds.

2021-11-01 13:26 UTC, Datseris commented on examples/growing_bacteria.jl
> +            all(0 .< a.p2 .< extent) && add_agent!(a.p2, model, 0.0, a.orientation, 0.0, 0.1 * rand(model.rng) + 0.05)
The 0 is allowed. you can have it equal to 0, just not equal to extent.

2021-11-01 13:37 UTC, Datseris approved these changes

2021-12-28 12:30 UTC, Datseris commented
@MichielStock thank you! In Agents.jl 5.0 all examples besides the 5 central ones to the library will be in a new repository called "Agents.jl Example Zoo". Can you please make this PR there instead? https://github.com/JuliaDynamics/Agents.jl_Example_Zoo

(please close this when you open the new PR)

2022-01-13 15:29 UTC, closed without merging