Rename functions like `genocide!`
JuliaDynamics/Agents.jl pull request #766
Opened 2023-03-08 15:37 UTC by MA-Ramirez

Closes #764  

genocide! --> remove_all!
kill_agent! --> remove_agent!
Unkillable --> Unremovable

2023-03-08 17:49 UTC, jacobusmmsmit commented
Thank you for raising this, it has a strong +1 from me. Firstly for the obvious reason of how (euphemistically) _unnecessary_ the current names are, but secondly the current wording goes against the naming convention that functions that do the opposite things should have opposite names. Hence, I believe that `remove` is the correct opposite of `add` and not `kill`.

2023-03-08 18:20 UTC, jacobusmmsmit requested changes
There are a few mentions of kill left in the docs.

2023-03-08 18:20 UTC, jacobusmmsmit commented on examples/optim.jl
> +# managed to reduce the infection rate by removing the infected.
```suggestion
# managed to reduce the infection rate by "removing" the infected.
```
Makes it sound more ominous and closer to the original joke.

2023-03-08 18:20 UTC, jacobusmmsmit commented on src/spaces/graph.jl
> +Remove node (i.e. position) `n` from the model's graph. All agents in that node are removed.
```suggestion
Remove node (i.e. position) `n` from the model's graph. All agents in that node are removed from the model.
```

2023-03-08 18:20 UTC, jacobusmmsmit commented on src/spaces/graph.jl
> +Remove node (i.e. position) `n` from the model's graph. All agents in that node are removed.
```suggestion
Remove node (i.e. position) `n` from the model's graph. All agents in that node are removed from the model.
```

2023-03-08 19:03 UTC, MA-Ramirez commented
@jacobusmmsmit thank you for the additional modifications. I thought all the files in docs were automatically generated by the scripts, so I didn't check them. 
Is there something I can do to allow the push to my branch? Or should I make the changes in the branch myself?

2023-03-08 19:09 UTC, jacobusmmsmit commented
Honestly, I don't have the definitive answer to either of your comments.
Wrt docs, your comment makes sense and if that's the case then I guess it LGTM.
Wrt git, I don't think you need to do anything and the problem seems to be on my end. Maybe someone else can suggest why I can't push to her branch?

2023-03-09 15:55 UTC, Datseris requested changes
fantastic, thank a lot. However, if I were to merge this as it is right now, it would break every single Agents.jl code out there because we are renaming functions that thousands of users use. You need to go to the src/deprecations.jl file and add deprecations for all changed API names. For example,

```
@deprecate UnkillableABM UnremovableABM
```
and so on and so forth. Also, please add a changelog entry for every API name that was changed.

Changes in the wording of docstrings or documentation pages do not need to be mentioned. Only changes in API names, i.e., names explicitly participating in `export` statements.

2023-03-10 15:27 UTC, jacobusmmsmit approved these changes
LGTM

2023-03-10 15:28 UTC, jacobusmmsmit commented
Wait hang on, shouldn't these changes go in v5.9 not v5.8 as it's already been released?

2023-03-10 15:30 UTC, jacobusmmsmit requested changes

2023-03-10 15:30 UTC, jacobusmmsmit commented on CHANGELOG.md
> +- New function `remove_all!` replaces `genocide!` (now deprecated).
Put these new changes in `main`

2023-03-10 15:32 UTC, jacobusmmsmit commented on CHANGELOG.md
> +- New function `remove_all!` replaces `genocide!` (now deprecated).
I hope my "request changes" doesn't seem too much like I'm bossing you around @MA-Ramirez! I don't like telling people what to do when I'm not super confident that it's the right thing, but I'm pretty sure `main` is the right place for these changes :')

2023-03-11 08:41 UTC, Datseris approved these changes

2023-03-11 08:49 UTC, merged

2025-08-21 11:55 UTC, xlejx-rodsxn commented
Hi, thanks for the quick reply to my comment. I found here on the API description:

https://juliadynamics.github.io/Agents.jl/v5.6/api/

Where can I find the latest documentation?

2025-08-21 11:57 UTC, Datseris commented
<img width="1032" height="876" alt="image" src="https://github.com/user-attachments/assets/786a745f-2edf-4e77-a5c4-1f1e785c4e26" />

2025-08-21 12:06 UTC, xlejx-rodsxn commented
Ah, weird. how did I end up in that version? anyway, thanks for taking care of this issue and the time invested in explaining.